# Generated by Django 5.2.5 on 2025-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Modelo')),
                ('assunto_email', models.CharField(max_length=200, verbose_name='Assunto do e-mail')),
                ('corpo_email', models.TextField(help_text='Você pode usar variáveis como {{ cliente.nome_razao }} e {{ cliente.cpf_cnpj }}.', verbose_name='Corpo do e-mail')),
                ('corpo_contrato', models.TextField(help_text='Use HTML básico e variáveis Jinja como {{ cliente.nome_razao }}.', verbose_name='Template do contrato (HTML)')),
                ('ativo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
