# Generated by Django 5.2.5 on 2025-10-11 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Informe CPF (11 dígitos) ou CNPJ (14 dígitos), apenas números.', regex='^(\\d{11}|\\d{14})$')], verbose_name='CPF/CNPJ')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('regime_trabalhista', models.CharField(choices=[('HORISTA', 'Horista'), ('CLT', 'CLT'), ('ESTAGIARIO', 'Estagiário'), ('PJ', 'PJ'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome', 'id'],
                'indexes': [models.Index(fields=['nome'], name='funcionario_nome_013b6e_idx'), models.Index(fields=['ativo'], name='funcionario_ativo_20b6c6_idx')],
            },
        ),
    ]
