# Generated by Django 5.2.5 on 2025-08-30 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Informe CPF (11 dígitos) ou CNPJ (14 dígitos), apenas números.', regex='^(\\d{11}|\\d{14})$')], verbose_name='CPF/CNPJ')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome', 'id'],
                'indexes': [models.Index(fields=['nome'], name='funcionario_nome_013b6e_idx'), models.Index(fields=['ativo'], name='funcionario_ativo_20b6c6_idx')],
            },
        ),
    ]
