# Generated by Django 5.2.5 on 2025-11-08 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_data_nascimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrativo'), ('FIN', 'Financeiro'), ('RH', 'Recursos Humanos'), ('OP', 'Operacional'), ('DIR', 'Diretoria'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=20, verbose_name='Cargo'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['cargo'], name='funcionario_cargo_af7415_idx'),
        ),
    ]
