# Generated by Django 4.2.23 on 2025-09-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='regime_trabalhista',
            field=models.CharField(choices=[('HORISTA', 'Horista'), ('CLT', 'CLT'), ('ESTAGIARIO', 'Estagiário'), ('PJ', 'PJ'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=20),
        ),
    ]
