# Generated by Django 5.2.5 on 2025-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='registro_cref',
            field=models.CharField(blank=True, max_length=30, verbose_name='Registro CREF'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tam_uniforme',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tamanho do Uniforme'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrativo'), ('FIN', 'Financeiro'), ('RH', 'Recursos Humanos'), ('PROF', 'Professor'), ('DIR', 'Diretoria'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='regime_trabalhista',
            field=models.CharField(choices=[('CLT_HORISTA', 'CLT Horista'), ('CLT_NORMAL', 'CLT Normal'), ('ESTAGIARIO', 'Estagiário'), ('PJ', 'Pessoa Jurídica'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=20, verbose_name='Regime Trabalhista'),
        ),
    ]
