# Generated by Django 4.2.23 on 2025-09-01 15:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('condominios', '0001_initial'),
        ('turmas', '0002_listapresenca_itempresenca_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria financeira',
                'verbose_name_plural': 'Categorias financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEBER', 'A Receber'), ('PAGAR', 'A Pagar')], max_length=8)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PARCIAL', 'Parcial'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10)),
                ('contraparte_nome', models.CharField(blank=True, max_length=255)),
                ('contraparte_doc', models.CharField(blank=True, max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.categoriafinanceira')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='clientes.cliente')),
                ('condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='condominios.condominio')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='funcionarios.funcionario')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Lançamento financeiro',
                'verbose_name_plural': 'Lançamentos financeiros',
                'ordering': ['-vencimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Baixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('forma', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO', 'Cartão'), ('BOLETO', 'Boleto'), ('TRANSF', 'Transferência'), ('OUTRO', 'Outro')], default='PIX', max_length=10)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='financeiro.lancamento')),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['tipo', 'status'], name='financeiro__tipo_48eec3_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['vencimento'], name='financeiro__vencime_3ef38b_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['cliente'], name='financeiro__cliente_94c5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['condominio'], name='financeiro__condomi_73dae2_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['funcionario'], name='financeiro__funcion_9507f6_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['turma'], name='financeiro__turma_i_7c5a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='baixa',
            index=models.Index(fields=['lancamento', 'data'], name='financeiro__lancame_da6039_idx'),
        ),
    ]
