# Generated by Django 5.2.5 on 2025-10-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('nome_razao', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone_emergencial', models.CharField(blank=True, max_length=20)),
                ('telefone_celular', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('numero_id', models.CharField(blank=True, max_length=20)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=False)),
                ('aceite_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('aceite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('aceite_confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='condominios.condominio')),
            ],
            options={
                'ordering': ['nome_razao', 'id'],
                'indexes': [models.Index(fields=['nome_razao'], name='clientes_cl_nome_ra_20dd62_idx'), models.Index(fields=['cpf_cnpj'], name='clientes_cl_cpf_cnp_0eeb49_idx'), models.Index(fields=['email'], name='clientes_cl_email_eae461_idx')],
            },
        ),
    ]
