# Generated by Django 4.2.23 on 2025-08-28 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Informe apenas dígitos: 11 para CPF ou 14 para CNPJ.', regex='^\\d{11}(\\d{3})?$|^\\d{14}$')], verbose_name='CPF/CNPJ')),
                ('nome_razao', models.CharField(max_length=255, verbose_name='Nome Completo / Razão Social')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone_emergencial', models.CharField(blank=True, max_length=20, verbose_name='Telefone Emergencial')),
                ('telefone_celular', models.CharField(blank=True, max_length=20, verbose_name='Telefone Celular')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('numero_id', models.CharField(blank=True, max_length=20, verbose_name='Número/ID')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('bairro', models.CharField(blank=True, max_length=255, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('municipio', models.CharField(blank=True, max_length=255, verbose_name='Município')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='Estado')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome_razao'],
            },
        ),
        migrations.CreateModel(
            name='VinculoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('RESPONSAVEL', 'Responsável'), ('DEPENDENTE', 'Dependente')], default='RESPONSAVEL', max_length=12)),
                ('tipo', models.CharField(choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('TUTOR', 'Tutor(a)'), ('CONJUGE', 'Cônjuge'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_saida', to='clientes.cliente')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_entrada', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Vínculo de Cliente',
                'verbose_name_plural': 'Vínculos de Clientes',
                'unique_together': {('responsavel', 'dependente', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='relacoes',
            field=models.ManyToManyField(related_name='relacionados', through='clientes.VinculoCliente', to='clientes.cliente'),
        ),
    ]
