# Generated by Django 4.2.23 on 2025-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_vinculocliente_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrato_aceito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrato_aceito_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrato_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrato_token_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
