# Generated by Django 4.2.23 on 2025-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_contrato_aceito_cliente_contrato_aceito_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
