# Generated by Django 5.2.5 on 2025-10-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_complemento'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='condominios.condominio'),
            preserve_default=False,
        ),
    ]
