# Generated by Django 5.2.5 on 2025-10-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_condominio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='contrato_aceito_em',
            new_name='aceite_confirmado_em',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='contrato_token_expira_em',
            new_name='aceite_expires_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contrato_aceito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contrato_token',
        ),
        migrations.AddField(
            model_name='cliente',
            name='aceite_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
