# Generated by Django 5.2.5 on 2025-10-11 19:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('condominios', '__first__'),
        ('funcionarios', '__first__'),
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(blank=True, max_length=255, verbose_name='Nome (opcional)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('capacidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade (máx. alunos)')),
                ('hora_inicio', models.TimeField(default='18:00')),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('seg', models.BooleanField(default=False, verbose_name='Seg')),
                ('ter', models.BooleanField(default=False, verbose_name='Ter')),
                ('qua', models.BooleanField(default=False, verbose_name='Qua')),
                ('qui', models.BooleanField(default=False, verbose_name='Qui')),
                ('sex', models.BooleanField(default=False, verbose_name='Sex')),
                ('sab', models.BooleanField(default=False, verbose_name='Sáb')),
                ('dom', models.BooleanField(default=False, verbose_name='Dom')),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='condominios.condominio')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='modalidades.modalidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['condominio__nome', 'modalidade__nome', 'hora_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('participante_nome', models.CharField(blank=True, max_length=255)),
                ('participante_cpf', models.CharField(blank=True, max_length=14)),
                ('participante_sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='clientes.cliente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='turmas.turma')),
            ],
            options={
                'ordering': ['-ativa', 'cliente__nome_razao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListaPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacao_geral', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_presenca', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Lista de presença',
                'verbose_name_plural': 'Listas de presença',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('cliente_nome_snapshot', models.CharField(max_length=255)),
                ('cliente_doc_snapshot', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencas', to='clientes.cliente')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='turmas.listapresenca')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presencas', to='turmas.matricula')),
            ],
            options={
                'verbose_name': 'Item de presença',
                'verbose_name_plural': 'Itens de presença',
                'ordering': ['cliente_nome_snapshot', 'id'],
                'indexes': [models.Index(fields=['lista'], name='turmas_item_lista_i_1f3be8_idx'), models.Index(fields=['cliente'], name='turmas_item_cliente_b9a4a5_idx')],
                'unique_together': {('lista', 'cliente')},
            },
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['professor', 'hora_inicio'], name='turmas_turm_profess_53ac68_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['condominio'], name='turmas_turm_condomi_68dda4_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['ativo'], name='turmas_turm_ativo_88fc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['turma', 'ativa'], name='turmas_matr_turma_i_7050cf_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['cliente'], name='turmas_matr_cliente_883a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='listapresenca',
            index=models.Index(fields=['turma', 'data'], name='turmas_list_turma_i_f2bda0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listapresenca',
            unique_together={('turma', 'data')},
        ),
    ]
