# Generated by Django 4.2.23 on 2025-09-01 12:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('modalidades', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(blank=True, max_length=255, verbose_name='Nome (opcional)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('capacidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade (máx. alunos)')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('duracao_minutos', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='condominios.condominio')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='modalidades.modalidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['condominio__nome', 'modalidade__nome', 'dia_semana', 'hora_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='clientes.cliente')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-ativa', 'turma', 'cliente__nome_razao'],
            },
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['professor', 'dia_semana', 'hora_inicio'], name='turmas_turm_profess_2e7e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['condominio'], name='turmas_turm_condomi_68dda4_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['ativo'], name='turmas_turm_ativo_88fc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['turma', 'ativa'], name='turmas_matr_turma_i_7050cf_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['cliente', 'ativa'], name='turmas_matr_cliente_973a9a_idx'),
        ),
    ]
