# Generated by Django 4.2.23 on 2025-09-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacao_geral', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_presenca', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Lista de presença',
                'verbose_name_plural': 'Listas de presença',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('cliente_nome_snapshot', models.CharField(max_length=255)),
                ('cliente_doc_snapshot', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencas', to='clientes.cliente')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='turmas.listapresenca')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presencas', to='turmas.matricula')),
            ],
            options={
                'verbose_name': 'Item de presença',
                'verbose_name_plural': 'Itens de presença',
                'ordering': ['cliente_nome_snapshot', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='listapresenca',
            index=models.Index(fields=['turma', 'data'], name='turmas_list_turma_i_f2bda0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listapresenca',
            unique_together={('turma', 'data')},
        ),
        migrations.AddIndex(
            model_name='itempresenca',
            index=models.Index(fields=['lista'], name='turmas_item_lista_i_1f3be8_idx'),
        ),
        migrations.AddIndex(
            model_name='itempresenca',
            index=models.Index(fields=['cliente'], name='turmas_item_cliente_b9a4a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itempresenca',
            unique_together={('lista', 'cliente')},
        ),
    ]
