# Generated by Django 5.2.5 on 2025-10-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='participante_idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='itempresenca',
            unique_together={('lista', 'matricula')},
        ),
        migrations.AddIndex(
            model_name='itempresenca',
            index=models.Index(fields=['matricula'], name='turmas_item_matricu_0fcd6a_idx'),
        ),
    ]
