# Generated by Django 4.2.23 on 2025-09-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_listapresenca_itempresenca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-ativa', 'cliente__nome_razao', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='matricula',
            name='turmas_matr_cliente_973a9a_idx',
        ),
        migrations.AddField(
            model_name='matricula',
            name='participante_cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='matricula',
            name='participante_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='matricula',
            name='participante_sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['cliente'], name='turmas_matr_cliente_883a4e_idx'),
        ),
    ]
