# Generated by Django 5.2.5 on 2025-10-13 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_matricula_participante_idade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['modalidade__condominio__nome', 'modalidade__nome', 'hora_inicio', 'id'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.RemoveIndex(
            model_name='turma',
            name='turmas_turm_condomi_68dda4_idx',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='condominio',
        ),
    ]
