# Generated by Django 4.2.23 on 2025-10-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0002_remove_modalidade_modalidades_nome_4bce1d_idx_and_more'),
        ('condominios', '0001_initial'),
        ('turmas', '0003_alter_matricula_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='condominios.condominio'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='modalidades.modalidade'),
        ),
    ]
