# Generated by Django 5.2.5 on 2025-11-08 16:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_alter_turma_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='bonificacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bonificação'),
        ),
        migrations.AddField(
            model_name='turma',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='turma',
            name='vale_transporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='VT/VA'),
        ),
        migrations.AddField(
            model_name='turma',
            name='valor_dsr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor + DSR'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Aula'),
        ),
    ]
