# Generated by Django 5.2.5 on 2025-11-08 23:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0004_turma_bonificacao_turma_observacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='participante_cpf',
        ),
        migrations.AddField(
            model_name='matricula',
            name='participante_data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='bonificacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bonificação'),
        ),
    ]
