# Generated by Django 5.2.5 on 2025-11-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_remove_matricula_participante_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapresenca',
            name='ocorrencia_aula',
            field=models.CharField(choices=[('NORMAL', 'Aula Normal'), ('FALTA_PROF', 'Falta do Professor'), ('CANCELADA', 'Aula Cancelada'), ('SUBSTITUIDO', 'Professor Substituído'), ('REPOSICAO', 'Aula de Reposição')], default='NORMAL', max_length=20, verbose_name='Ocorrência da aula'),
        ),
    ]
