# Generated by Django 4.2.23 on 2025-10-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='modalidade',
            name='modalidades_nome_4bce1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='modalidade',
            name='modalidades_ativo_5b0aca_idx',
        ),
        migrations.AddField(
            model_name='modalidade',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='condominios.condominio', verbose_name='Condomínio'),
        ),
        migrations.AddConstraint(
            model_name='modalidade',
            constraint=models.UniqueConstraint(fields=('condominio', 'nome'), name='uniq_modalidade_por_condominio_nome'),
        ),
    ]
